## Default configuration for bsc_sniper.

# Modify these values to tune the behaviour of the bot. All values are
# examples and are not used by the current skeleton code.

# Example configuration
discovery:
  min_liquidity_bnb: 10
  excluded_tokens:
    - 0x0000000000000000000000000000000000000000

trading:
  max_fee_percentage: 5.0
  stop_loss: -10.0
  take_profit: 10.0

telegram:
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "YOUR_TELEGRAM_CHAT_ID"
